fastboot: fix warning
Fix the following warning:

drivers/fastboot/fb_getvar.c:184:21: warning: implicit declaration of function ‘run_command’ [-Wimplicit-function-declaration]
                   if (run_command(c, 0))
                       ^~~~~~~~~~~

Fixes: 0269d97649e6 ("fastboot: implement current-slot")
Signed-off-by: Fabien Parent <fparent@baylibre.com>