Revert "usb-ehci: Support interrupt transfers via periodic list"
Reverted by sheriff due to tree-closing compile error:
chromeos-u-boot-0.0.1-r361: ehci-hcd.c:1188:2: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]

This reverts commit 5b4448f574a4510e81df3210028d45695e5f620c

Change-Id: Id7468ad5b651cee6287e3913dac23d9093e411b3
Reviewed-on: https://gerrit.chromium.org/gerrit/13681
Commit-Ready: Greg Spencer <gspencer@chromium.org>
Reviewed-by: Greg Spencer <gspencer@chromium.org>
Tested-by: Greg Spencer <gspencer@chromium.org>