RFC: efi: Drop code that doesn't work with driver model
This code should never have been added as it builds a new feature on top
of legacy code. This has already been improved with the dependency on BLK.

Add a dependency on DM_ETH also, to avoid needing to deal with this old
code.

Boards which want EFI_LOADER should migrate to driver model first.

Note this patch is included to resolve the following build error:

lib/efi_loader/efi_runtime.c:680:16: error: ‘CONFIG_SYS_TEXT_BASE’
	undeclared (first use in this function); did you mean
	‘CONFIG_SYS_SRAM_BASE’?
  680 |   ulong base = CONFIG_SYS_TEXT_BASE;
      |                ^~~~~~~~~~~~~~~~~~~~
      |                CONFIG_SYS_SRAM_BASE

Series-changes: 2
- Put this patch first so that it is separated from the rest of the series
- Mention why this patch is included in this series

Signed-off-by: Simon Glass <sjg@chromium.org>
Change-Id: Id572ddf5eb457096b95d30ae2d8675f539367fe8