tools: patman: Handle missing 'END' in non-last commit of a series
The following python error:

Traceback (most recent call last):
  File "./tools/patman/patman", line 144, in <module>
    series = patchstream.FixPatches(series, args)
  File "./tools/patman/patchstream.py", line 477, in FixPatches
    commit = series.commits[count]
IndexError: list index out of range

is seen when:

- 'END' is missing in those tags
- those tags are put in the last part in a commit message
- the commit is not the last commit of the series

Add testing logic to see if a new commit starts.

Signed-off-by: Bin Meng <bmeng.cn@gmail.com>

Series-changes: 2
- New patch to handle missing 'END' in non-last commit of a series
Cover-letter:
tools: patman: Fixes to improve handling of various wrong usage
This fixes several issues when abnormal tags are given to patman.
For example, when we forget to put an 'END' after 'Cover-letter',
patman does not handle such cases very well. This adds several
additional checking to let patman be a little more tolerant on
handling such exceptional paths.

This series is available at u-boot-x86/patman-working for testing.
END