dts: Generate binaries for all relevant platforms
Similar targets can use the same u-boot binary with different device
trees. It is convenient to have all similar device trees compiled and
published when u-boot is made: it allows for later easy repackaging
without the need to re-run the make file.

This follows the Linux kernel suite, which also compiles all similar
device tree targets at once.

For the purposes of exynos u-boot, as of now similar targets are those
which have the same device tree file prefix (before the first '-').

This change modifies the dts makefile to allow concurrent processing
of multiple device trees. As previously, one device tree is still
published at 'u-boot.dtb', this is a copy of the compiled default
device tree.

The problem with some DTC compiler versions generating stderr output
even when there is no compilation errors has been also addressed: all
DTC output is collected in a file, and only in case of error is the
file sent to stderr.

BRANCH=none
BUG=chrome-os-partner:18329
TEST=manual
  . emerge-{link|daisy} chromeos-u-boot - both succeed

  . to verify that all device tres get compiled run the following
    commands (the doit script below configures and builds u-boot for
    the target passed through TARGET='):

    $ rm -rf /tmp/u-*
    $ for t in link peach daisy; do
       USE_STDINT=1 U_BOOT_ROOT=$(pwd)  TARGET=$t doit
      done
    $ find /tmp/u-* -name '*.dtb'
   /tmp/u-daisy/u-boot.dtb
   /tmp/u-daisy/dts/exynos5250-snow.dtb
   /tmp/u-daisy/dts/exynos5250-smdk5250.dtb
   /tmp/u-daisy/dts/exynos5250-spring.dtb
   /tmp/u-link/u-boot.dtb
   /tmp/u-link/dts/link.dtb
   /tmp/u-peach/u-boot.dtb
   /tmp/u-peach/dts/exynos5420-smdk5420.dtb
   /tmp/u-peach/dts/exynos5420-peach_pit.dtb
   /tmp/u-peach/dts/exynos5420-peach-pit-adv.dtb

  . to verify that dt.o still builds when required run the following
    commands

   $ find /tmp/u-peach/ -name 'dt.o'
   $ CONFIG_OF_EMBED=y   TARGET=peach USE_STDINT=1 U_BOOT_ROOT=$(pwd)  doit
   $ find /tmp/u-peach/ -name 'dt.o'
   /tmp/u-peach/dts/dt.o

  . to verify that corrupting device tree still stops the build, add a
    syntax error to exynos5420-peach_pit.dts and rerun the build:

   $ TARGET=peach USE_STDINT=1 U_BOOT_ROOT=$(pwd)  doit
   Building in /tmp/u-peach
   DTC: dts->dtb  on file "/tmp/u-peach/dts/exynos5420-peach_pit.dtb.in"
   FATAL ERROR: Unable to parse input tree
   Error: /tmp/u-peach/dts/exynos5420-peach_pit.dtb.in:6.1-4 syntax error
   make[1]: *** [/tmp/u-peach/dts/exynos5420-peach_pit.dtb] Error 1
   make[1]: Target 'binary' not remade because of errors.
   make: *** [/tmp/u-peach/u-boot.dtb] Error 2
   make: Target `all' not remade because of errors.

Change-Id: I401f18758c77676bced9334be735a114ed0ad659
Signed-off-by: Vadim Bendebury <vbendeb@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/57652

Signed-off-by: Andrew Chew <achew@nvidia.com>
Change-Id: I02a10eda004f6c7f5425e97a3e646acddc1529ac
Reviewed-on: https://gerrit.chromium.org/gerrit/58228
Reviewed-by: Vadim Bendebury <vbendeb@chromium.org>